#!/bin/sh

STATION_TYPE=`grep station_type /etc/genesis_ping.conf | cut -d " " -f 2`
GENESIS_ADDRESS=`grep address /etc/genesis_ping.conf | cut -d " " -f 2`
LOCKFILE=/var/run/genesis_ping

run() {
    trap "rm -f ${LOCKFILE}; exit" INT TERM EXIT
    i=60
    while true
    do
        if [ $i -eq 60 ]; then
            genesis_ping ${GENESIS_ADDRESS} ${STATION_TYPE} > /dev/null 2>&1
            i=0
        fi
        i=$((i+1))
        sleep 1
    done
    rm -f $LOCKFILE
}

stop_running() {
    if [ ! -e ${LOCKFILE} ]; then
        echo "${LOCKFILE} not found. Probably not running."
    else
        kill -s TERM `cat ${LOCKFILE}`
    fi
}

start_running() {
    if [ -e ${LOCKFILE} ] && kill -0 `cat ${LOCKFILE}`; then
        echo "Already running."
        exit
    fi
    run &
    echo $! > ${LOCKFILE}
}

case $1 in
    start)
        start_running
        ;;
    stop)
        stop_running
        ;;
    restart)
        stop_running
        start_running
        ;;
    *)
        echo "Use: start stop restart"
        exit 1
        ;;
esac
